import pandas as pd
import matplotlib.pyplot as plt
import os

# Load the CSV file generated by TensorBoard
# Replace 'path_to_your_file.csv' with the path to your TensorBoard CSV file
csv_file_path = 'NCCL.csv'

# Extract the base name of the CSV file (without the extension) to use for the image name
base_name = os.path.splitext(os.path.basename(csv_file_path))[0]

# Read the CSV file into a DataFrame
df = pd.read_csv(csv_file_path)

# Check the columns in the CSV file (optional, to understand the structure)
print(df.columns)

# Extract the 'Step' and 'Value' columns
steps = df['Step']  # Column for steps
values = df['Value']  # Column for values (e.g., loss, accuracy)

# Plot the relationship between Step and Value
plt.figure(figsize=(10, 6))
plt.plot(steps, values, label='Value vs Step', color='red')

# Add labels and title
plt.xlabel('Step')
plt.ylabel('Loss')
plt.title('NCCL Train Loss Curve')
plt.legend()

# Add gridlines to the plot
plt.grid(True)

# Save the plot as an image with the same name as the CSV file (but with a .png extension)
image_file_path = f'{base_name}.png'
plt.savefig(image_file_path, dpi=400)

# Optionally, display the plot (if you want to view it in the script as well)
# plt.show()

# Print a message to indicate the image has been saved
print(f"Plot saved as '{image_file_path}'")
